
#Absolutely Stuffed! Just Desserts
[Tuning]
	#How much can fit in the player's pool (0 = 2^31-1). Keep in mind that 40 is a full hunger and saturation bar.
	#Range: 0 ~ 160
	max_pool_size = 0
	#How many ticks to wait before attempting to fill the hunger / saturation bars from the pool (20 = 1 second).
	#Range: 1 ~ 200
	pool_tick_rate = 5

